"""Fake Gmail data for demo mode (no real Gmail connection)."""

DEMO_EMAIL = "demo@example.com"

MOCK_MESSAGES = [
    {
        "id": "m1", "thread_id": "t1",
        "from": "Sarah Chen <sarah@acme.co>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Lunch this week?",
        "snippet": "Are you free Wednesday or Thursday for lunch? I have an idea I want to run by you.",
        "date": "Wed, 14 May 2026 10:32:00 -0700",
        "body": "Hey,\n\nAre you free Wednesday or Thursday for lunch? I have an idea I want to run by you about the Q3 roadmap.\n\nWhat works on your end?\n\nSarah",
        "message_id_header": "<sarah-1@acme.co>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m2", "thread_id": "t2",
        "from": "Marcus Webb <marcus@oldfriend.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Quick question about the contract",
        "snippet": "Just reviewing the SOW. Section 3.2 — is the 30-day notice mutual or one-way?",
        "date": "Wed, 14 May 2026 14:15:00 -0700",
        "body": "Hi,\n\nJust reviewing the SOW. Section 3.2 — is the 30-day notice mutual or one-way? Want to make sure we're aligned before we sign.\n\nThanks,\nMarcus",
        "message_id_header": "<marcus-2@oldfriend.com>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m3", "thread_id": "t3",
        "from": "Priya Patel <priya@boardroom.io>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "ACTION REQUIRED: Board materials due Friday EOD",
        "snippet": "Please review and sign off on the attached board deck by Friday EOD.",
        "date": "Wed, 14 May 2026 09:00:00 -0700",
        "body": "Team,\n\nPlease review and sign off on the attached board deck by Friday EOD. Marking up directly in the doc is fine.\n\nPriya",
        "message_id_header": "<priya-3@boardroom.io>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": True,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m4", "thread_id": "t4",
        "from": "Calendar <noreply@calendar.google.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Invitation: Design review @ Thu May 15, 2026 2pm",
        "snippet": "You have been invited to Design review on Thursday May 15 at 2:00pm.",
        "date": "Wed, 14 May 2026 11:00:00 -0700",
        "body": "You have been invited to:\n\nDesign review\nThursday May 15, 2026 2:00pm - 3:00pm PT\nConference room 3 / Zoom\n\nOrganizer: alex@acme.co",
        "message_id_header": "<cal-4@calendar.google.com>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": True,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m5", "thread_id": "t5",
        "from": "Stripe <updates@stripe.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Your weekly payout summary",
        "snippet": "Your payout of $4,231.18 was sent to your bank.",
        "date": "Wed, 14 May 2026 06:00:00 -0700",
        "body": "Your payout of $4,231.18 was sent to your bank account ending in 4242 on May 14. View details in your dashboard.",
        "message_id_header": "<stripe-5@stripe.com>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD", "CATEGORY_UPDATES"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m6", "thread_id": "t6",
        "from": "GitHub <notifications@github.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "[acme/api] CI passed on PR #482",
        "snippet": "All checks have passed on your pull request.",
        "date": "Wed, 14 May 2026 12:42:00 -0700",
        "body": "All checks have passed on your pull request #482 'Refactor billing pipeline'.\n\nView on GitHub.",
        "message_id_header": "<gh-6@github.com>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m7", "thread_id": "t7",
        "from": "The Pragmatic Engineer <newsletter@substack.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "How big tech runs incident reviews",
        "snippet": "This week: a deep dive into how Google, Stripe, and Cloudflare run blameless postmortems.",
        "date": "Wed, 14 May 2026 05:30:00 -0700",
        "body": "This week: a deep dive into how Google, Stripe, and Cloudflare run blameless postmortems.\n\nRead online | Unsubscribe",
        "message_id_header": "<newsletter-7@substack.com>",
        "references": "",
        "list_unsubscribe": "<mailto:unsub@substack.com>",
        "labels": ["INBOX", "UNREAD", "CATEGORY_UPDATES"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m8", "thread_id": "t8",
        "from": "Morning Brew <crew@morningbrew.com>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Markets close mixed, Nvidia keeps climbing",
        "snippet": "Good morning. Stocks closed mixed yesterday as investors weighed earnings...",
        "date": "Wed, 14 May 2026 06:01:00 -0700",
        "body": "Good morning. Stocks closed mixed yesterday as investors weighed earnings season against fresh inflation data.",
        "message_id_header": "<mb-8@morningbrew.com>",
        "references": "",
        "list_unsubscribe": "<https://unsub.morningbrew.com/abc>",
        "labels": ["INBOX", "UNREAD", "CATEGORY_PROMOTIONS"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m9", "thread_id": "t9",
        "from": "Jordan Liu <jordan@startup.io>",
        "to": DEMO_EMAIL, "cc": "",
        "subject": "Re: intro to our investor",
        "snippet": "Got it, thanks for the warm intro. Will reach out today. Talk soon!",
        "date": "Wed, 14 May 2026 13:20:00 -0700",
        "body": "Got it, thanks for the warm intro. Will reach out today.\n\nTalk soon!\nJordan",
        "message_id_header": "<jordan-9@startup.io>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
    {
        "id": "m10", "thread_id": "t10",
        "from": "Emma Rodriguez <emma@design.co>",
        "to": DEMO_EMAIL, "cc": "alex@acme.co",
        "subject": "Logo concepts — which direction?",
        "snippet": "Pinging on the three logo directions I sent Monday. Any thoughts on which way to push further?",
        "date": "Wed, 14 May 2026 15:45:00 -0700",
        "body": "Hey,\n\nPinging on the three logo directions I sent Monday. Any thoughts on which way to push further? Happy to iterate on any of them — just want to make sure we land on the right one before I go deep.\n\nEmma",
        "message_id_header": "<emma-10@design.co>",
        "references": "",
        "list_unsubscribe": "",
        "labels": ["INBOX", "UNREAD"],
        "has_attachments": False,
        "is_calendar": False,
        "me_email": DEMO_EMAIL,
    },
]


class MockService:
    """Stand-in for the Gmail API service object."""

    def get_messages(self):
        return list(MOCK_MESSAGES)

    def get_email(self):
        return DEMO_EMAIL
